### PR TITLE
Fix privacy breach in documentation.

### PR DESCRIPTION
**Pull request by mzf-guest**
In the HTML documentation, some pictures are loaded from external sources, hence creating a privacy breach for the user browsing the documentation.

This pull request replaces the two dynamic images by some text. An other approach could be to embed the images in the installation. Feel free to update the code!

Thanks,

### CODE REVIEW

**Comment by AlexisWilke** [comment]
Ah. We should move the images to the Doxygen output.

These should be in the `doc/...` folder and in the doxy file we can add the necessary so they get copied to the output. Then update the HTML output accordingly.

**Comment by AlexisWilke** [comment]
Okay, I applied a fix to those sections. Different from what you offered, but the issue should be resolved. Feel free to reopen if you still get an error.

**Comment by mzf-guest** [comment]
Thanks!

Please note there is one remainder call to external website for "Download Zipios" picture [here](https://github.com/Zipios/Zipios/blob/95c8e5dda871277192769e98256c905814d211c1/src/zipfile.cpp#L202).

Could you please also remove it to avoid privacy breach?

**Comment by AlexisWilke** [comment]
Sorry, I applied one more fix. I also noticed I was missing a file. Now we should be good.

**Comment by mzf-guest** [comment]
Thanks!

**Pull request closed without merging**
