### PR TITLE
cmake update & appstream file

### PR DESCRIPTION
**Pull request by sevu**
Changes:
- Adds an file containing meta information.
- Removes workarounds for cmake 2.8.4.
- Addresses the todo regarding the ZipiosConfig file. I can't comment on the file itself though.

Some remarks:
- Ideally the ID in the metainfo file would be sth. alike net.sourceforge.zipios.Zipios.
- You probably can get rid of the FindCatch.cmake file, catch provides a CatchConfig.cmake file [itself](https://www.archlinux.org/packages/community/any/catch2/files).
- Current git version is 2.2.1.0. The CmakeLists.txt calls the last digit the build level, and it's not used, I suggest dropping it altogether.

It might be a while until I respond for feedback, no worries.
Btw, where is the software used, or whom does it aim for?

### CODE REVIEW

**Comment by AlexisWilke** [comment]
This looks fine. I found a page about this XML file: https://wiki.debian.org/AppStream/Guidelines

What exactly does it give you? Since `zipios` is a library, I'm not too sure I understand how it helps...

**Comment by AlexisWilke** [comment]
About `FindCatch.cmake`, it can still be useful if you want to use the library under MS-Windows which doesn't have installation schemes like we do under Linux.

The version includes a build number because we have such for [Snap! C++](https://snapwebsites.org/), which is an example of an app. using zipios. Also, when we build on launchpad, we at times make a change to a dependency (zipios is a dependency of some other libraries/tools for us) and have to force a rebuild. We increment the build number in that case (if we make no other changes, of course.)

As for who else uses it, I have no clue. _They_ do not say. You? :-)

**Comment by dooglio** [comment]
> utACK

Means "untested ACK", meaning that the changes look good but I haven't tested anything.

**Comment by AlexisWilke** [comment]
Okay, I applied part of the changes here to the master branch. I hope it helps.

**Comment by AlexisWilke** [comment]
This has been applied manually a while back. So closing.

**Pull request closed without merging**
